version: '3.5'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: savio
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2021!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2021!
    links:
      - mongo
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB:/data/db
    networks:
      - ${GLOBAL_NETWORK:-kafka}
#
#networks:
#  mongo-compose-network:
#    driver: bridge